# Generated by Django 6.0.4 on 2026-04-30 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_project_category_projectimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField(help_text='Pourcentage (0-100)')),
                ('category', models.CharField(choices=[('dev', 'Développement'), ('bio', 'Biomédical'), ('it', 'IT & Réseaux'), ('soft', 'Soft Skills')], max_length=20)),
            ],
        ),
    ]
